// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3Qa6q3s1gm91eHXRuPwyBY
// Component: 5S4FajIL-oi
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsglmAo6RxnuGek } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: GlmAO6RxnuGek/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_lexyom_site_v_1.module.css"; // plasmic-import: 3Qa6q3s1gm91eHXRuPwyBY/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: 5S4FajIL-oi/css
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: RPw95Ru86uio/icon
import InstagramSvgrepoComsvgIcon from "./icons/PlasmicIcon__InstagramSvgrepoComsvg"; // plasmic-import: F74gsTp3W4/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: rLQx_Fb_DoC7/icon
import FacebookSvgrepoComsvgIcon from "./icons/PlasmicIcon__FacebookSvgrepoComsvg"; // plasmic-import: k5aL1_VQsZ/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: ai-qmtX9bxdJ/icon

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsglmAo6RxnuGek()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__lWkWi)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__uTToB)}
        >
          <p.PlasmicLink
            className={classNames(projectcss.all, projectcss.a, sty.link__eQFk)}
            component={Link}
            href={"/"}
            platform={"nextjs"}
          >
            <p.PlasmicImg
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto"}
              displayMaxHeight={"40px"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              src={{
                src: "/plasmic/lexyom_site_v_1/images/logoV3Png.png",
                fullWidth: 354,
                fullHeight: 112,
                aspectRatio: undefined
              }}
            />
          </p.PlasmicLink>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__cmtfo)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jlVvx
              )}
            >
              {"Connect with us"}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___4SFTc)}
            >
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__th4Cu
                )}
                component={Link}
                href={"https://twitter.com/lexyomlaw?lang=en"}
                platform={"nextjs"}
                target={"_blank"}
              >
                <Icon5Icon
                  className={classNames(projectcss.all, sty.svg__waEz)}
                  role={"img"}
                />
              </p.PlasmicLink>

              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__fvGw8
                )}
                component={Link}
                href={"https://www.instagram.com/lexyomlaw/"}
                platform={"nextjs"}
                target={"_blank"}
              >
                <InstagramSvgrepoComsvgIcon
                  className={classNames(projectcss.all, sty.svg__qFaWw)}
                  role={"img"}
                />
              </p.PlasmicLink>

              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__vfMyt
                )}
                component={Link}
                href={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "https://www.linkedin.com/company/18214534/"
                    : undefined
                }
                platform={"nextjs"}
                target={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "_blank"
                    : undefined
                }
              >
                <Icon28Icon
                  className={classNames(projectcss.all, sty.svg__a7Rqi)}
                  role={"img"}
                />
              </p.PlasmicLink>

              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__gpYv
                )}
                component={Link}
                href={"https://www.facebook.com/lexyomlaw/"}
                platform={"nextjs"}
                target={"_blank"}
              >
                <FacebookSvgrepoComsvgIcon
                  className={classNames(projectcss.all, sty.svg__dVpuc)}
                  role={"img"}
                />
              </p.PlasmicLink>
            </p.Stack>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__gnDTu)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___8FsSr
            )}
          >
            {"Product"}
          </div>

          <p.Stack
            as={p.PlasmicLink}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.link___1Fl5B
            )}
            component={Link}
            platform={"nextjs"}
          >
            {false ? (
              <Icon4Icon
                className={classNames(projectcss.all, sty.svg__oTZeL)}
                role={"img"}
              />
            ) : null}

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__gqpt5
              )}
              component={Link}
              href={"/pricing"}
              platform={"nextjs"}
            >
              {"Pricing"}
            </p.PlasmicLink>

            {false ? (
              <Icon4Icon
                className={classNames(projectcss.all, sty.svg__z0SEu)}
                role={"img"}
              />
            ) : null}
          </p.Stack>

          <p.Stack
            as={p.PlasmicLink}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.link__zrfMa
            )}
            component={Link}
            platform={"nextjs"}
          >
            {false ? (
              <Icon4Icon
                className={classNames(projectcss.all, sty.svg__k7YgO)}
                role={"img"}
              />
            ) : null}

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__sY5X3
              )}
              component={Link}
              href={"/our-story"}
              platform={"nextjs"}
            >
              {"About Us"}
            </p.PlasmicLink>

            {false ? (
              <Icon4Icon
                className={classNames(projectcss.all, sty.svg__e4L6U)}
                role={"img"}
              />
            ) : null}
          </p.Stack>

          <p.Stack
            as={p.PlasmicLink}
            hasGap={true}
            className={classNames(projectcss.all, projectcss.a, sty.link__sor0)}
            component={Link}
            platform={"nextjs"}
          >
            {false ? (
              <Icon4Icon
                className={classNames(projectcss.all, sty.svg__aPdsr)}
                role={"img"}
              />
            ) : null}

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__lRkzt
              )}
              component={Link}
              platform={"nextjs"}
            >
              {"Terms and Conditions"}
            </p.PlasmicLink>

            {false ? (
              <Icon4Icon
                className={classNames(projectcss.all, sty.svg__badxJ)}
                role={"img"}
              />
            ) : null}
          </p.Stack>

          <p.Stack
            as={p.PlasmicLink}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.link__oc3Mi
            )}
            component={Link}
            platform={"nextjs"}
          >
            {false ? (
              <Icon4Icon
                className={classNames(projectcss.all, sty.svg__j5X6O)}
                role={"img"}
              />
            ) : null}

            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link___9Lb7T
              )}
              component={Link}
              platform={"nextjs"}
            >
              {"Privacy Policy"}
            </p.PlasmicLink>

            {false ? (
              <Icon4Icon
                className={classNames(projectcss.all, sty.svg__jd4Mn)}
                role={"img"}
              />
            ) : null}
          </p.Stack>
        </p.Stack>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
